version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ltrack_production
      POSTGRES_USER: ltrack_user
      POSTGRES_PASSWORD: ltrack_secure_production_password_2024
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: