services:
  - type: web
    name: ltrack-backend
    env: node
    region: oregon
    plan: free
    buildCommand: cd backend && npm install && npm run build
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: file:./dev.db
      - key: JWT_SECRET
        value: your-jwt-secret-key-minimum-32-characters-long-for-security
      - key: ENCRYPTION_KEY
        value: your-32-character-encryption-key!!
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        sync: false

  - type: web
    name: ltrack-frontend
    env: static
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_URL
        sync: false
